catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

#ask Paul or Jay for clarification...

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #we gon define all of our app-level urls
    #we needa add an import statement to link our files

    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cats/', views.cats_index, name='index'),
    path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
    path('cats/create/', views.CatCreate.as_view(), name='cats_create'),
    path('Cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
    path('Cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
    path('cats/<int:cat_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    path('cats/<int:cat_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


# A tuple of 2-tuples
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)


class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})


class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    # Add the M:M relationship
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    #changes 
    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('detail', kwargs={'cat_id': self.id})




class Feeding(models.Model):
  date = models.DateField('Feeding Date')
  meal = models.CharField(
    max_length=1,
	 choices=MEALS,
	 default=MEALS[0][0]
  )
  # Create a cat_id FK
  cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_meal_display()} on {self.date}"

    # change the default sort
  class Meta:
    ordering = ['-date']



class Photo(models.Model):
  url = models.CharField(max_length=200)
  cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for cat_id: {self.cat_id} @{self.url}" 

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from multiprocessing import context
from nis import cat
from pyexpat import model
from django.shortcuts import render, redirect
# from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from .models import Cat, Toy, Photo
from .forms import FeedingForm
import boto3
import uuid

#Env Variables
S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'cat-collector-king'


def signup(request):
    # handle POST requests (signup)
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect ('index')
        else: 
            error_message = 'invalid credentials - please try again'

    # handle GET request (navigate user to sign up page)
    form = UserCreationForm()
    context = {'form': form, 'error': error_message }
    return render(request, 'registration/signup.html', context )


# Create your views here.
# def home(request):
#     return HttpResponse('<h1>Hello World!!!</h1>')
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')



# # Add the Cat class & list and view function below the imports
# class Cat:  # Note that parens are optional if not inheriting from another class
#   def __init__(self, name, breed, description, age):
#     self.name = name
#     self.breed = breed
#     self.description = description
#     self.age = age

# cats = [
#   Cat('Lolo', 'tabby', 'foul little demon', 3),
#   Cat('Sachi', 'tortoise shell', 'diluted tortoise shell', 0),
#   Cat('Raven', 'black tripod', '3 legged cat', 4),
#   Cat('Rocket', 'Siamese', 'looks like rufus from kim possible', 70),
# ]
@login_required
def cats_index(request):
    cats = Cat.objects.filter(user=request.user)
    return render(request,'cats/index.html', { 'cats': cats })


# def cats_detail(request, cat_id):
#     cat = Cat.objects.get(id=cat_id)
#     return render(request, 'cats/detail.html', {'cat': cat })

# update this view function
@login_required
def cats_detail(request, cat_id):
  cat = Cat.objects.get(id=cat_id)
  if cat.user_id != request.user.id:
      return redirect('index')
  # instantiate FeedingForm to be rendered in the template
  feeding_form = FeedingForm()
  return render(request, 'cats/detail.html', {
    # include the cat and feeding_form in the context
    'cat': cat, 'feeding_form': feeding_form
  })



# add this new function below cats_detail
@login_required
def add_feeding(request, cat_id):
  # create the ModelForm using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.cat_id = cat_id
    new_feeding.save()
  return redirect('detail', cat_id=cat_id)





@login_required
def add_photo(request, cat_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            photo = Photo(url=url, cat_id=cat_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', cat_id=cat_id)







class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = ('name', 'breed', 'description', 'age')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    """success_url = '/cats/'"""


class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = ('breed', 'description', 'age')

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    success_url = '/cats/'


class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = ('name', 'color')

class ToyUpdate(LoginRequiredMixin, UpdateView):
    model = Toy
    fields = ('name', 'color')

class ToyDelete(LoginRequiredMixin, DeleteView):
    model = Toy
    success_url = '/toys/'

class ToyDetail(LoginRequiredMixin, DetailView):
    model = Toy
    template_name = 'toys/detail.html'

class ToyList(LoginRequiredMixin, ListView):
    model = Toy
    template_name = 'toys/index.html'

main_app/templates/about.html
{% extends 'base.html' %} 

{% block content %}
<h1>About the Cat Collector</h1>
<hr />
<p>Hire the Cat Collector</p>
<!-- <footer>All Rights Reserved, &copy; 2022 Cat Collector</footer> -->
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Cat Collector</title>
    <!--Link to our materializing css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!--Link to static css-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li>
                        <a href="/" class="left brand-logo"> CatCollector</a>
                    </li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{%url 'index' %}">View All My Cats</a></li>
                    <li><a href="{%url 'cats_create' %}">Add a Cat</a></li>
                    <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
                    <li><a href="{% url 'toys_index' %}">View All My Toys</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Log In</a></li>
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
        <div class="right">
            All Rights Reserved, &copy; 2022 Cat Collector &nbsp;
        </div>
    </footer>
</body>

</html>

main_app/templates/cats/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Cat Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ cat.name }}</span>
                <p>Breed: {{ cat.breed }}</p>
                <p>Description: {{ cat.description }}</p>
                {% if cat.age > 0 %}
                <p>Age: {{ cat.age }}</p>
                {% else %}
                <p>Age: Kitten</p>
                {% endif %}
            </div>
            <div class="card-action">
                <a href="{% url 'cats_update' cat.id %}">Edit</a>
                <a href="{% url 'cats_delete' cat.id %}">Delete</a>
            </div>
        </div>
        {% for photo in cat.photo_set.all %}
        <img src="{{ photo.url }}" alt="{{ cat.name }}" class="responsive-img card-panel">
        {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
        <form action="{% url 'add_photo' cat.id %}" method="POST" enctype="multipart/form-data" class="card-panel">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <br>
            <br>
            <input type="submit" value="Upload Photo" class="btn green">
        </form>
    </div>
    <div class="col s6">
        <form action="{% url 'add_feeding' cat.id %}" method="post">
            {% csrf_token %} {{ feeding_form.as_p }}
            <input type="submit" class="btn green" value="Add Feeding" />
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Meal</th>
                </tr>
            </thead>
            <tbody>
                {% for feeding in cat.feeding_set.all %}
                <tr>
                    <td>{{feeding.date}}</td>
                    <td>{{feeding.get_meal_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script>
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    // add additional JS to initialize select below
    var selectEl = document.getElementById('id_meal');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %} {% block content %}

<h1>Cat List</h1>

{% for cat in cats %}
<div class="card">
    <a href="{% url 'detail' cat.id %}">
        <div class="card-content">
            <span class="card-title">{{ cat.name }}</span>
            <p>Breed: {{ cat.breed }}</p>
            <p>Description: {{ cat.description }}</p>
            {% if cat.age > 0 %}
            <p>Age: {{ cat.age }}</p>
            {% else %}
            <p>Age: Kitten</p>
            {% endif %}
        </div>
    </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} 

{% block content %}
<h1>This is the Cat Collector Home page</h1>
{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Are you sure you want to remove {{ object.name}}</h1>
<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Remove">
    <a class= "btn blue" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %}

{% block content %}


<form action="" method="post">
    <!--we always have to use this tag in forms-->
    {% csrf_token %}
<table>
    {{ form.as_table }}
</table>

    <input class="btn green" type="submit" value="add Cats">
</form>

{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Toy</h1>

<h4>
    Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Update {{ object.name }}</h1>
{% else %}
    <h1>Add Toy</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="{% if object %} Update Toy {% else %} Add Toy {% endif %}">
</form>

{% endblock %}

main_app/templates/toys/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Toy Details</h1>


<div class="card">
    <a href="{% url 'toys_detail' toy.id %}">
        <div class="card-content">
            <span class="card-title">A <span class="{{ toy.color.lower }}-text">{{ toy.color }}</span> {{ toy.name }}</span>
        </div>
        <div class="card-action">
            <a href="{% url 'toys_update' toy.id %}">Edit</a>
            <a href="{% url 'toys_delete' toy.id %}">Delete</a>
        </div>
    </a>
</div>

{% endblock %}

main_app/templates/toys/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Toys List</h1>
{% for toy in object_list %}
<div class="card">
    <a href="{% url 'toys_detail' toy.id %}">
        <div class="card-content">
            <span class="card-title">A <span class="{{ toy.color }}-text"></span> {{ toy.name }}</span>
        </div>
    </a>
</div>
{% endfor %}


{% endblock %}